services:
  trading-bot:
    build:
      context: ./bitcoinTrader
    image: trading-bot
    container_name: trading-bot
    ports:
      - "8080:8080"
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
    volumes:
      - bot-data:/app/data
volumes:
  bot-data: {}
